CREATE TABLE PUBLIC.T_OWNER(
    ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)
);
ALTER TABLE PUBLIC.T_OWNER ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);

CREATE TABLE PUBLIC.T_PET(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    BIRTH_DATE DATE,
    OWNER_ID BIGINT
);
ALTER TABLE PUBLIC.T_PET ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);

ALTER TABLE PUBLIC.T_PET ADD  CONSTRAINT public.CONSTRAINT_3 FOREIGN KEY(OWNER_ID)  REFERENCES PUBLIC.T_OWNER(ID);

CREATE SEQUENCE PUBLIC.PETCLINIC_SEQUENCE START WITH 100;

CREATE  TABLE USERS(
USERNAME VARCHAR(100) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR (512) NOT NULL,
ENABLED BOOLEAN NOT NULL
);

CREATE TABLE AUTHORITIES(
USERNAME VARCHAR(100) NOT NULL,
AUTHORITY VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX IDX_AUTH_USERNAME ON AUTHORITIES(USERNAME,AUTHORITY);

